name: ci-workflow-typescript-test
on: [push]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      #add comment
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
     
      
