name: ci-workflow-typescript-test
on: [push]
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      #set node version
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

     
      
